on: push
name: Test retire
jobs:
  build:
    name: Test retire
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn global add retire
      - run: pwd
      - run: retire ./

